// Script is generated by AI (gemini-3-pro), code-style and boilerplate reflects that...
import fs from "fs";
import path from "path";

const SOURCES = [
  "tallinn.json",
  "parkimine-ee.json",
  "europark.json",
  "snabb.json",
];

const DATA_JSON_PATH = "../Data.json";

async function main() {
  console.log(`Reading ${DATA_JSON_PATH}...`);
  // Use path.resolve to match current working directory assumption
  // If run from Data/scripts, ../Data.json is correct.
  const dataPath = path.resolve(process.cwd(), DATA_JSON_PATH);

  if (!fs.existsSync(dataPath)) {
    throw new Error(`Data file not found at ${dataPath}`);
  }

  const dataJsonRaw = fs.readFileSync(dataPath, "utf-8");
  const dataJson = JSON.parse(dataJsonRaw);

  let allZones: unknown[] = [];

  for (const source of SOURCES) {
    const sourcePath = path.resolve(process.cwd(), source);
    console.log(`Reading ${source}...`);
    if (fs.existsSync(sourcePath)) {
      const sourceRaw = fs.readFileSync(sourcePath, "utf-8");
      try {
        const sourceData = JSON.parse(sourceRaw);
        if (Array.isArray(sourceData)) {
          allZones = allZones.concat(sourceData);
        } else {
          console.warn(`Warning: ${source} is not an array, skipping.`);
        }
      } catch (e) {
        console.error(`Error parsing ${source}:`, e);
      }
    } else {
      console.warn(`Warning: ${source} not found at ${sourcePath}, skipping.`);
    }
  }

  // Update data.zones
  if (!dataJson.data) {
    dataJson.data = {};
  }
  dataJson.data.zones = allZones;

  // Write back
  console.log(`Writing merged data to ${dataPath}...`);
  fs.writeFileSync(dataPath, JSON.stringify(dataJson, null, 4));
  console.log("Done.");
}

main().catch(console.error);
